package cn.et.lesson03.food.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.SID
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.SNAME
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.SEX
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.AGE
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ADDRESS
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.SID
     *
     * @return the value of student.SID
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.SID
     *
     * @param sid the value for student.SID
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.SNAME
     *
     * @return the value of student.SNAME
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.SNAME
     *
     * @param sname the value for student.SNAME
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.SEX
     *
     * @return the value of student.SEX
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.SEX
     *
     * @param sex the value for student.SEX
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.AGE
     *
     * @return the value of student.AGE
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.AGE
     *
     * @param age the value for student.AGE
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ADDRESS
     *
     * @return the value of student.ADDRESS
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ADDRESS
     *
     * @param address the value for student.ADDRESS
     *
     * @mbg.generated Mon Dec 11 11:40:06 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}